export const POPULAR_LANGUAGES = [
    'text', 'markdown', 'plaintext', 'javascript', 'typescript', 'python', 'java', 'c', 'cpp', 'csharp', 'go', 'rust', 'php', 'ruby', 'swift', 'kotlin', 'html', 'css', 'scss', 'sass', 'json', 'yaml', 'sql', 'bash', 'shell', 'docker', 'dockerfile'
];

export const COMPREHENSIVE_LANGUAGES = [
    'text', 'markdown', 'plaintext', 'javascript', 'typescript', 'jsx', 'tsx', 'python', 'java', 'c', 'cpp', 'csharp', 'go', 'rust', 'php', 'ruby', 'swift', 'kotlin', 'scala', 'dart', 'r', 'perl', 'lua', 'bash', 'shell', 'sh', 'zsh', 'powershell', 'sql', 'plsql', 'tsql', 'mysql', 'postgresql', 'sqlite', 'html', 'css', 'scss', 'sass', 'less', 'stylus', 'json', 'yaml', 'yml', 'xml', 'toml', 'ini', 'conf', 'csv', 'graphql', 'protobuf', 'thrift', 'dockerfile', 'docker', 'makefile', 'cmake', 'nginx', 'apache', 'diff', 'patch', 'git', 'haskell', 'elixir', 'erlang', 'clojure', 'lisp', 'scheme', 'racket', 'ocaml', 'fsharp', 'reasonml', 'elm', 'purescript', 'solidity', 'vyper', 'assembly', 'asm', 'nasm', 'llvm', 'wasm', 'webassembly', 'fortran', 'cobol', 'ada', 'pascal', 'delphi', 'vb', 'vbnet', 'objectivec', 'matlab', 'julia', 'coffeescript', 'livescript', 'nim', 'crystal', 'zig', 'v', 'groovy', 'gradle', 'terraform', 'hcl', 'bicep', 'pug', 'jade', 'haml', 'handlebars', 'mustache', 'twig', 'ejs', 'erb', 'jinja', 'jinja2', 'django', 'velocity', 'latex', 'tex', 'bibtex', 'rmarkdown', 'rst', 'restructuredtext', 'asciidoc', 'org', 'textile', 'mediawiki', 'bbcode', 'arduino', 'processing', 'verilog', 'vhdl', 'systemverilog', 'tcl', 'expect', 'awk', 'sed', 'gawk', 'actionscript', 'applescript', 'autohotkey', 'autoit', 'batch', 'bat', 'brainfuck', 'chapel', 'd', 'eiffel', 'factor', 'forth', 'hack', 'inform7', 'j', 'lolcode', 'malbolge', 'monkey', 'monkey-c', 'nix', 'pawn', 'pike', 'postscript', 'prolog', 'q', 'qml', 'rexx', 'ring', 'robot', 'smalltalk', 'sml', 'tcsh', 'vala', 'apex', 'abap', 'apl', 'ballerina', 'bnf', 'bsl', 'ceylon', 'clean', 'cool', 'cypher', 'dtrace', 'dylan', 'idris', 'io', 'isabelle', 'jsonc', 'json5', 'jsonld', 'jsonnet', 'logos', 'mathematica', 'mermaid', 'nimrod', 'nushell', 'nu', 'pddl', 'pegjs', 'puppet', 'qsharp', 'reasonligo', 'red', 'regx', 'rego', 'rescript', 'smithy', 'sparql', 'smt', 'stan', 'stata', 'svelte', 'tla', 'ttcn', 'vba', 'vue', 'wgsl', 'wolfram', 'wren', 'xquery', 'yang', 'zenscript', 'dot', 'plantuml'
];

export interface LanguageOption {
    value: string;
    label: string;
    isCategory?: boolean;
}

export const LANGUAGE_DROPDOWN_OPTIONS: LanguageOption[] = [
    { value: '', label: 'Most Popular & Daily Use', isCategory: true },
    { value: 'text', label: 'Plain Text' },
    { value: 'markdown', label: 'Markdown' },
    { value: 'javascript', label: 'JavaScript' },
    { value: 'typescript', label: 'TypeScript' },
    { value: 'python', label: 'Python' },
    { value: 'java', label: 'Java' },
    { value: 'c', label: 'C' },
    { value: 'cpp', label: 'C++' },
    { value: 'csharp', label: 'C#' },
    { value: 'go', label: 'Go' },
    { value: 'rust', label: 'Rust' },
    { value: 'php', label: 'PHP' },
    { value: 'ruby', label: 'Ruby' },
    { value: 'swift', label: 'Swift' },
    { value: 'kotlin', label: 'Kotlin' },
    { value: 'html', label: 'HTML' },
    { value: 'css', label: 'CSS' },
    { value: 'scss', label: 'SCSS' },
    { value: 'sass', label: 'Sass' },
    { value: 'json', label: 'JSON' },
    { value: 'yaml', label: 'YAML' },
    { value: 'xml', label: 'XML' },
    { value: 'sql', label: 'SQL' },
    { value: 'bash', label: 'Bash' },
    { value: 'shell', label: 'Shell' },
    { value: 'dockerfile', label: 'Dockerfile' },
    { value: 'docker', label: 'Docker' },

    { value: '', label: 'Web & Frontend', isCategory: true },
    { value: 'jsx', label: 'JSX (React)' },
    { value: 'tsx', label: 'TSX (React TypeScript)' },
    { value: 'vue', label: 'Vue' },
    { value: 'svelte', label: 'Svelte' },
    { value: 'less', label: 'Less' },
    { value: 'stylus', label: 'Stylus' },

    { value: '', label: 'Mobile Development', isCategory: true },
    { value: 'dart', label: 'Dart' },
    { value: 'objectivec', label: 'Objective-C' },

    { value: '', label: 'JVM & Enterprise', isCategory: true },
    { value: 'scala', label: 'Scala' },
    { value: 'groovy', label: 'Groovy' },
    { value: 'gradle', label: 'Gradle' },
    { value: 'apex', label: 'Apex (Salesforce)' },

    { value: '', label: 'Functional Languages', isCategory: true },
    { value: 'haskell', label: 'Haskell' },
    { value: 'elixir', label: 'Elixir' },
    { value: 'erlang', label: 'Erlang' },
    { value: 'clojure', label: 'Clojure' },
    { value: 'lisp', label: 'Lisp' },
    { value: 'scheme', label: 'Scheme' },
    { value: 'racket', label: 'Racket' },
    { value: 'ocaml', label: 'OCaml' },
    { value: 'fsharp', label: 'F#' },
    { value: 'elm', label: 'Elm' },
    { value: 'purescript', label: 'PureScript' },
    { value: 'reasonml', label: 'ReasonML' },
    { value: 'rescript', label: 'ReScript' },

    { value: '', label: 'Shell & Scripting', isCategory: true },
    { value: 'sh', label: 'sh' },
    { value: 'zsh', label: 'Zsh' },
    { value: 'powershell', label: 'PowerShell' },
    { value: 'batch', label: 'Batch' },
    { value: 'bat', label: 'BAT' },
    { value: 'nushell', label: 'Nushell' },
    { value: 'nu', label: 'Nu' },

    { value: '', label: 'Data & Configuration', isCategory: true },
    { value: 'plaintext', label: 'Plaintext' },
    { value: 'jsonc', label: 'JSON with Comments' },
    { value: 'json5', label: 'JSON5' },
    { value: 'jsonld', label: 'JSON-LD' },
    { value: 'jsonnet', label: 'Jsonnet' },
    { value: 'yml', label: 'YML' },
    { value: 'toml', label: 'TOML' },
    { value: 'ini', label: 'INI' },
    { value: 'conf', label: 'Config' },
    { value: 'csv', label: 'CSV' },

    { value: '', label: 'Database & Query Languages', isCategory: true },
    { value: 'plsql', label: 'PL/SQL' },
    { value: 'tsql', label: 'T-SQL' },
    { value: 'mysql', label: 'MySQL' },
    { value: 'postgresql', label: 'PostgreSQL' },
    { value: 'sqlite', label: 'SQLite' },
    { value: 'graphql', label: 'GraphQL' },
    { value: 'sparql', label: 'SPARQL' },
    { value: 'cypher', label: 'Cypher (Neo4j)' },

    { value: '', label: 'Infrastructure & DevOps', isCategory: true },
    { value: 'terraform', label: 'Terraform' },
    { value: 'hcl', label: 'HCL' },
    { value: 'bicep', label: 'Bicep' },
    { value: 'nginx', label: 'Nginx' },
    { value: 'apache', label: 'Apache' },
    { value: 'makefile', label: 'Makefile' },
    { value: 'cmake', label: 'CMake' },

    { value: '', label: 'Template Engines', isCategory: true },
    { value: 'pug', label: 'Pug' },
    { value: 'jade', label: 'Jade' },
    { value: 'haml', label: 'HAML' },
    { value: 'handlebars', label: 'Handlebars' },
    { value: 'mustache', label: 'Mustache' },
    { value: 'twig', label: 'Twig' },
    { value: 'ejs', label: 'EJS' },
    { value: 'erb', label: 'ERB' },
    { value: 'jinja', label: 'Jinja' },
    { value: 'jinja2', label: 'Jinja2' },
    { value: 'django', label: 'Django Template' },
    { value: 'velocity', label: 'Velocity' },

    { value: '', label: 'Markup & Documentation', isCategory: true },
    { value: 'latex', label: 'LaTeX' },
    { value: 'tex', label: 'TeX' },
    { value: 'bibtex', label: 'BibTeX' },
    { value: 'rmarkdown', label: 'RMarkdown' },
    { value: 'rst', label: 'reStructuredText' },
    { value: 'restructuredtext', label: 'reStructuredText (full)' },
    { value: 'asciidoc', label: 'AsciiDoc' },
    { value: 'org', label: 'Org Mode' },
    { value: 'textile', label: 'Textile' },
    { value: 'mediawiki', label: 'MediaWiki' },
    { value: 'bbcode', label: 'BBCode' },

    { value: '', label: 'Scientific Computing', isCategory: true },
    { value: 'r', label: 'R' },
    { value: 'julia', label: 'Julia' },
    { value: 'matlab', label: 'MATLAB' },
    { value: 'mathematica', label: 'Mathematica' },
    { value: 'wolfram', label: 'Wolfram' },
    { value: 'stata', label: 'Stata' },
    { value: 'stan', label: 'Stan' },

    { value: '', label: 'Blockchain & Web3', isCategory: true },
    { value: 'solidity', label: 'Solidity' },
    { value: 'vyper', label: 'Vyper' },

    { value: '', label: 'Assembly & Low-Level', isCategory: true },
    { value: 'assembly', label: 'Assembly' },
    { value: 'asm', label: 'ASM' },
    { value: 'nasm', label: 'NASM' },
    { value: 'llvm', label: 'LLVM' },
    { value: 'wasm', label: 'WebAssembly' },
    { value: 'webassembly', label: 'WebAssembly (full)' },
    { value: 'wgsl', label: 'WGSL' },

    { value: '', label: 'Hardware Description', isCategory: true },
    { value: 'verilog', label: 'Verilog' },
    { value: 'vhdl', label: 'VHDL' },
    { value: 'systemverilog', label: 'SystemVerilog' },
    { value: 'arduino', label: 'Arduino' },
    { value: 'processing', label: 'Processing' },

    { value: '', label: 'Legacy & Classic', isCategory: true },
    { value: 'fortran', label: 'Fortran' },
    { value: 'cobol', label: 'COBOL' },
    { value: 'ada', label: 'Ada' },
    { value: 'pascal', label: 'Pascal' },
    { value: 'delphi', label: 'Delphi' },
    { value: 'vb', label: 'Visual Basic' },
    { value: 'vbnet', label: 'VB.NET' },
    { value: 'vba', label: 'VBA' },

    { value: '', label: 'Specialized Languages', isCategory: true },
    { value: 'perl', label: 'Perl' },
    { value: 'lua', label: 'Lua' },
    { value: 'tcl', label: 'Tcl' },
    { value: 'awk', label: 'AWK' },
    { value: 'gawk', label: 'GAWK' },
    { value: 'sed', label: 'Sed' },
    { value: 'abap', label: 'ABAP' },
    { value: 'apl', label: 'APL' },
    { value: 'applescript', label: 'AppleScript' },
    { value: 'autohotkey', label: 'AutoHotkey' },
    { value: 'autoit', label: 'AutoIt' },
    { value: 'ballerina', label: 'Ballerina' },
    { value: 'chapel', label: 'Chapel' },
    { value: 'coffeescript', label: 'CoffeeScript' },
    { value: 'crystal', label: 'Crystal' },
    { value: 'd', label: 'D' },
    { value: 'dylan', label: 'Dylan' },
    { value: 'hack', label: 'Hack' },
    { value: 'idris', label: 'Idris' },
    { value: 'j', label: 'J' },
    { value: 'nim', label: 'Nim' },
    { value: 'nimrod', label: 'Nimrod' },
    { value: 'nix', label: 'Nix' },
    { value: 'prolog', label: 'Prolog' },
    { value: 'puppet', label: 'Puppet' },
    { value: 'qsharp', label: 'Q#' },
    { value: 'red', label: 'Red' },
    { value: 'rego', label: 'Rego' },
    { value: 'ring', label: 'Ring' },
    { value: 'smalltalk', label: 'Smalltalk' },
    { value: 'v', label: 'V' },
    { value: 'vala', label: 'Vala' },
    { value: 'zig', label: 'Zig' },

    { value: '', label: 'Data Formats & Protocols', isCategory: true },
    { value: 'protobuf', label: 'Protocol Buffers' },
    { value: 'thrift', label: 'Thrift' },
    { value: 'bnf', label: 'BNF' },

    { value: '', label: 'Diagrams & Visualization', isCategory: true },
    { value: 'mermaid', label: 'Mermaid' },
    { value: 'dot', label: 'DOT (Graphviz)' },
    { value: 'plantuml', label: 'PlantUML' },

    { value: '', label: 'Version Control', isCategory: true },
    { value: 'diff', label: 'Diff' },
    { value: 'patch', label: 'Patch' },
    { value: 'git', label: 'Git' },

    { value: '', label: 'Other Languages', isCategory: true },
    { value: 'actionscript', label: 'ActionScript' },
    { value: 'brainfuck', label: 'Brainfuck' },
    { value: 'factor', label: 'Factor' },
    { value: 'forth', label: 'Forth' },
    { value: 'io', label: 'Io' },
    { value: 'lolcode', label: 'LOLCODE' },
    { value: 'monkey', label: 'Monkey' },
    { value: 'postscript', label: 'PostScript' },
    { value: 'qml', label: 'QML' },
    { value: 'rexx', label: 'REXX' },
    { value: 'sml', label: 'SML' },
    { value: 'wren', label: 'Wren' },
    { value: 'xquery', label: 'XQuery' },

    { value: 'custom', label: 'Custom (type below)' }
];
