import type { PluginSettings } from './core/interfaces';
import { DEFAULT_PRETTIER_CONFIG } from './utils/prettierConfig';

export const DEFAULT_SETTINGS: PluginSettings = {
    enableAutoFormat: true,
    enableLinting: true,
    formatOnSave: false,
    showLintErrors: true,
    autoFixLintIssues: true,
    prettierConfig: DEFAULT_PRETTIER_CONFIG,
    postProcessingConfig: {
        enableListFormatting: true,
        enableLineTrimmingInLists: true,
        enableCodeBlockFormatting: true,
        enableTocGeneration: false,
        tocDepth: 3,
        tocPosition: 'after-frontmatter',
        codeBlockLanguages: ['javascript', 'typescript', 'python', 'bash', 'shell', 'json', 'yaml', 'css', 'scss', 'html'],
        removeDuplicateBlankLines: true,
    },
    lintRules: {
        noTrailingSpaces: true,
        noMultipleBlankLines: true,
        requireBlankLineBeforeHeading: true,
        requireBlankLineAfterHeading: true,
        headingStyle: 'atx',
        emphasisMarker: 'consistent',
        strongMarker: 'consistent',
        defaultCodeLanguage: 'text',
        headingIncrement: true,
        noDuplicateHeadings: true,
        singleH1: true,
        noTrailingPunctuationInHeading: true,
        firstLineH1: false,
        unorderedListStyle: 'asterisk',
        orderedListStyle: 'ordered',
        listMarkerSpace: true,
        blankLinesAroundLists: true,
        blankLinesAroundFences: true,
        codeBlockStyle: 'fenced',
        codeFenceStyle: 'backtick',
        noBareUrls: false,
        noAltText: true,
        filesEndWithNewline: true,
    },
};