import type { PluginSettings } from './core/interfaces';
import { DEFAULT_PRETTIER_CONFIG } from './utils/prettierConfig';

export const DEFAULT_SETTINGS: PluginSettings = {
    enableAutoFormat: true,
    enableLinting: true,
    formatOnSave: false,
    showLintErrors: true,
    autoFixLintIssues: true,
    prettierConfig: DEFAULT_PRETTIER_CONFIG,
    postProcessingConfig: {
        enableListFormatting: true,
        enableLineTrimmingInLists: true,
        enableCodeBlockFormatting: true,
        enableTocGeneration: false,
        tocDepth: 3,
        tocPosition: 'after-frontmatter',
        codeBlockLanguages: ['javascript', 'typescript', 'python', 'bash', 'shell', 'json', 'yaml', 'css', 'scss', 'html'],
        removeDuplicateBlankLines: true,
    },
    lintRules: {
        noTrailingSpaces: true,
        noMultipleBlankLines: true,
        requireBlankLineBeforeHeading: true,
        requireBlankLineAfterHeading: true,
        headingStyle: 'atx',
        emphasisMarker: 'consistent',
        strongMarker: 'consistent',
        defaultCodeLanguage: 'text',
        headingIncrement: true,
        noDuplicateHeadings: true,
        singleH1: true,
        noTrailingPunctuationInHeading: true,
        firstLineH1: false,
        unorderedListStyle: 'asterisk',
        orderedListStyle: 'ordered',
        listMarkerSpace: true,
        blankLinesAroundLists: true,
        blankLinesAroundFences: true,
        codeBlockStyle: 'fenced',
        codeFenceStyle: 'backtick',
        noBareUrls: false,
        noAltText: true,
        filesEndWithNewline: true,
    },
    uiConfig: {
        modalDisplayDelay: 100,
        maxAutoFixIterations: 10,
        formatOnSaveDelay: 0,
        statusBarOpacity: {
            disabled: 0.5,
            active: 1.0,
            idle: 0.8,
        },
    },
    lintAdvancedConfig: {
        brSpaces: 2,
        maxBlankLines: 1,
        headingLinesAbove: 1,
        headingLinesBelow: 1,
        listMarkerSpaces: 1,
        tabIndent: 1,
    },
    designSystem: {
        fontSize: {
            small: '0.9em',
            medium: '1em',
            large: '1.1em',
        },
        spacing: {
            button: '8px 16px',
            tab: '12px 24px',
            badge: '2px 8px',
        },
        animation: {
            transitionDuration: '0.2s',
            transitionEasing: 'ease',
        },
    },
};