import type { PluginSettings } from './types';
import { DEFAULT_PRETTIER_CONFIG } from './utils/prettierConfig';

export const DEFAULT_SETTINGS: PluginSettings = {
    enableAutoFormat: true,
    enableLinting: true,
    formatOnSave: false,
    showLintErrors: true,
    autoFixLintIssues: true,
    prettierConfig: DEFAULT_PRETTIER_CONFIG,
    lintRules: {
        noTrailingSpaces: true,
        noMultipleBlankLines: true,
        requireBlankLineBeforeHeading: true,
        requireBlankLineAfterHeading: true,
        headingStyle: 'atx',
        emphasisMarker: 'consistent',
        strongMarker: 'consistent',
        defaultCodeLanguage: 'text',
        headingIncrement: true,
        noDuplicateHeadings: true,
        singleH1: true,
        noTrailingPunctuationInHeading: true,
        firstLineH1: false,
        unorderedListStyle: 'asterisk',
        orderedListStyle: 'ordered',
        listMarkerSpace: true,
        blankLinesAroundLists: true,
        blankLinesAroundFences: true,
        codeBlockStyle: 'fenced',
        codeFenceStyle: 'backtick',
        noBareUrls: false,
        noAltText: true,
        filesEndWithNewline: true,
    },
};